export interface ArticleMeta {
  slug: string;
  title: string;
  description: string;
  category: 'maintenance' | 'ride-planning' | 'cycling-basics';
  tags: string[];
  datePublished: string;
  dateModified: string;
  heroImage: string;
  heroImageAlt: string;
  author: string;
  schemaType: 'Article' | 'HowTo' | 'FAQPage';
  readingTime: number;
  related: string[];
}

export const articles: ArticleMeta[] = [
  {
    slug: 'bike-tune-up-cost',
    title: "Bike Tune-Up Cost: What Shops Charge & What's Included",
    description:
      "Bike tune-up cost by tier: basic ($50–$100), standard ($100–$180), and overhaul ($200+). What's included, what parts cost extra, and which tier you need.",
    category: 'cycling-basics',
    tags: ['bike tune up cost', 'bike tune up price', 'bicycle tune up', 'bike shop pricing', 'bike service cost'],
    datePublished: '2026-07-03',
    dateModified: '2026-07-03',
    heroImage: '/images/articles/bike-tune-up-cost.webp',
    heroImageAlt: 'Bike mechanic working on a bicycle drivetrain at a workbench in a professional shop',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 8,
    related: ['bike-maintenance-schedule', 'how-long-do-bike-parts-last', 'how-to-buy-a-used-bike'],
  },
  {
    slug: 'how-to-buy-a-used-bike',
    title: 'How to Buy a Used Bike: Inspection Checklist & Red Flags',
    description:
      "How to buy a used bike without regret: pricing research, a full inspection checklist, test-ride checks, and how to negotiate on wear you find yourself.",
    category: 'cycling-basics',
    tags: ['how to buy a used bike', 'used bike checklist', 'used bike inspection', 'buying a used bicycle', 'bike red flags'],
    datePublished: '2026-07-02',
    dateModified: '2026-07-02',
    heroImage: '/images/articles/how-to-buy-a-used-bike.webp',
    heroImageAlt: "Person inspecting a used bicycle's drivetrain and frame at a bike shop before purchase",
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 9,
    related: ['how-to-measure-chain-wear', 'how-long-do-bike-parts-last', 'bike-maintenance-for-beginners'],
  },
  {
    slug: 'bike-maintenance-for-beginners',
    title: 'Bike Maintenance for Beginners: The 8 Skills That Matter',
    description:
      'Learn the 8 bike maintenance skills every rider needs, a starter tool kit under $100, and the service cadence that keeps your bike running smoothly.',
    category: 'cycling-basics',
    tags: ['bike maintenance for beginners', 'beginner bike maintenance', 'bike care basics', 'bike tools', 'M-check'],
    datePublished: '2026-07-01',
    dateModified: '2026-07-01',
    heroImage: '/images/articles/bike-maintenance-for-beginners.webp',
    heroImageAlt: 'Cyclist performing basic maintenance on a clean bicycle outdoors with tools laid out nearby',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 8,
    related: ['bike-maintenance-schedule', 'how-to-measure-chain-wear', 'pre-ride-bike-check'],
  },
  {
    slug: 'bikepacking-for-beginners',
    title: 'Bikepacking for Beginners: Plan Your First Overnighter',
    description:
      'Start bikepacking with the S24O method: gear, bags, route tips, and a pre-trip service checklist so your first overnighter goes as planned.',
    category: 'ride-planning',
    tags: ['bikepacking for beginners', 'bikepacking', 'bike camping', 'overnighter', 'S24O'],
    datePublished: '2026-06-30',
    dateModified: '2026-06-30',
    heroImage: '/images/articles/bikepacking-for-beginners.webp',
    heroImageAlt: 'Bikepacker riding a loaded mountain bike on a dirt trail at sunrise with full bag setup and scenic landscape',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 8,
    related: ['how-to-plan-a-bike-ride', 'what-to-bring-on-a-bike-ride', 'cycling-route-planning-apps', 'bike-maintenance-schedule'],
  },
  {
    slug: 'cycling-in-the-rain',
    title: 'Cycling in the Rain: Riding Tips & Post-Ride Bike Care',
    description:
      'Wet-road braking, cornering, visibility, and the 10-minute post-rain routine that keeps chain wear from tripling. Ride safely and protect your bike.',
    category: 'ride-planning',
    tags: ['cycling in the rain', 'wet weather cycling', 'rain riding tips', 'bike maintenance', 'wet lube'],
    datePublished: '2026-06-29',
    dateModified: '2026-06-29',
    heroImage: '/images/articles/cycling-in-the-rain.webp',
    heroImageAlt: 'Cyclist riding on a wet glistening road in the rain, water droplets visible on the bike and road surface',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['how-to-plan-a-bike-ride', 'when-to-replace-bike-chain', 'when-to-replace-brake-pads', 'tubeless-sealant-how-often'],
  },
  {
    slug: 'group-ride-tips',
    title: 'Group Ride Tips: Etiquette, Signals & How Not to Get Dropped',
    description:
      'New to group riding? Learn ride categories, paceline basics, hand signals, and the unwritten rules that keep everyone safe and rolling together.',
    category: 'ride-planning',
    tags: ['group riding', 'cycling etiquette', 'paceline', 'cycling tips', 'beginner cycling'],
    datePublished: '2026-06-28',
    dateModified: '2026-06-28',
    heroImage: '/images/articles/group-ride-tips.webp',
    heroImageAlt: 'Group of cyclists riding in a tight paceline on a sunny road, wearing colorful cycling kit',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['how-to-plan-a-bike-ride', 'pre-ride-bike-check', 'what-to-bring-on-a-bike-ride'],
  },
  {
    slug: 'prepare-for-a-long-bike-ride',
    title: 'How to Prepare for a Long Bike Ride (Training to Tune-Up)',
    description:
      'Build up distance safely, nail your fueling and pacing, and get your bike ready weeks ahead — a complete prep guide for your longest rides yet.',
    category: 'ride-planning',
    tags: ['how to prepare for a long bike ride', 'cycling long ride prep', 'fueling for cycling', 'cycling training', 'bike prep'],
    datePublished: '2026-06-27',
    dateModified: '2026-06-27',
    heroImage: '/images/articles/prepare-for-a-long-bike-ride.webp',
    heroImageAlt:
      'Two cyclists riding on a wide open mountain road with dramatic landscape and clear sky, outdoor natural lighting',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 8,
    related: ['how-to-plan-a-bike-ride', 'pre-ride-bike-check', 'what-to-bring-on-a-bike-ride', 'bike-maintenance-schedule'],
  },
  {
    slug: 'cycling-route-planning-apps',
    title: 'Best Cycling Route Planners: Strava, Komoot, RWGPS & More',
    description:
      'Strava Routes, Komoot, and Ride with GPS compared: features, pricing, surface-type data, and which app fits your riding so you can pick one and use it.',
    category: 'ride-planning',
    tags: ['cycling route planner', 'Strava Routes', 'Komoot', 'Ride with GPS', 'route planning'],
    datePublished: '2026-06-26',
    dateModified: '2026-06-26',
    heroImage: '/images/articles/cycling-route-planning-apps.webp',
    heroImageAlt:
      'Cyclist checking a GPS navigation device mounted on handlebars on a scenic mountain trail, natural outdoor lighting',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 8,
    related: ['how-to-plan-a-bike-ride', 'strava-tips-for-cyclists'],
  },
  {
    slug: 'what-to-bring-on-a-bike-ride',
    title: 'What to Bring on a Bike Ride: Packing Lists by Distance',
    description:
      'Exactly what to pack for rides under 1 hour, 1–3 hours, and all-day: repair kit essentials, food and water math, and gear differences by discipline.',
    category: 'ride-planning',
    tags: ['what to bring on a bike ride', 'cycling packing list', 'bike ride essentials', 'cycling gear', 'repair kit'],
    datePublished: '2026-06-25',
    dateModified: '2026-06-25',
    heroImage: '/images/articles/what-to-bring-on-a-bike-ride.webp',
    heroImageAlt:
      'Cycling gear flat-lay on a surface: pump, multitool, tube, energy bars, water bottle, and phone, natural lighting',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['how-to-plan-a-bike-ride', 'pre-ride-bike-check', 'prepare-for-a-long-bike-ride'],
  },
  {
    slug: 'pre-ride-bike-check',
    title: 'The 5-Minute Pre-Ride Bike Check (M-Check Guide)',
    description:
      'Run a 5-minute M-check before every ride: step-by-step from front axle to rear brake, with tire pressure by discipline and what each finding means.',
    category: 'ride-planning',
    tags: ['pre ride bike check', 'M-check', 'pre-ride inspection', 'bike safety check', 'cycling safety'],
    datePublished: '2026-06-24',
    dateModified: '2026-06-24',
    heroImage: '/images/articles/pre-ride-bike-check.webp',
    heroImageAlt:
      'Cyclist in helmet inspecting bicycle brake and wheel before a ride, ready to go, outdoor natural lighting',
    author: 'KOR Cycling Team',
    schemaType: 'HowTo',
    readingTime: 7,
    related: ['how-to-plan-a-bike-ride', 'bike-maintenance-schedule', 'when-to-replace-bike-tires'],
  },
  {
    slug: 'how-to-plan-a-bike-ride',
    title: 'How to Plan a Bike Ride: Route, Gear & Bike Prep',
    description:
      'Plan any bike ride the right way: match distance to fitness, pick a route, fuel correctly, pack smart, and run a pre-ride check — with checklists to copy.',
    category: 'ride-planning',
    tags: ['bike ride planning', 'cycling route planning', 'cycling kit', 'pre-ride check', 'fueling for cycling'],
    datePublished: '2026-06-23',
    dateModified: '2026-06-23',
    heroImage: '/images/articles/how-to-plan-a-bike-ride.webp',
    heroImageAlt:
      'Two cyclists on a scenic mountain road with wide valley landscape and clear blue sky, outdoor natural lighting',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 11,
    related: [
      'pre-ride-bike-check',
      'what-to-bring-on-a-bike-ride',
      'cycling-route-planning-apps',
      'prepare-for-a-long-bike-ride',
      'group-ride-tips',
      'cycling-in-the-rain',
      'bikepacking-for-beginners',
      'bike-maintenance-schedule',
    ],
  },
  {
    slug: 'how-long-do-bike-parts-last',
    title: 'How Long Do Bike Parts Last? Lifespan of Every Component',
    description:
      'Chain, cassette, brake pads, tires, suspension, and more — real mileage ranges for every major bike component and the warning signs that beat any calendar.',
    category: 'maintenance',
    tags: ['bike parts lifespan', 'component replacement', 'bike maintenance', 'chain wear', 'bike longevity'],
    datePublished: '2026-06-22',
    dateModified: '2026-06-22',
    heroImage: '/images/articles/how-long-do-bike-parts-last.webp',
    heroImageAlt:
      'Collection of bicycle components laid out on a workshop surface — chain, cassette, brake pads, tires, and suspension parts',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 11,
    related: [
      'bike-maintenance-schedule',
      'when-to-replace-bike-chain',
      'when-to-replace-cassette',
      'when-to-replace-brake-pads',
      'when-to-replace-bike-tires',
      'suspension-service-intervals',
    ],
  },
  {
    slug: 'bottom-bracket-creaking',
    title: 'Bottom Bracket Creaking? Diagnosis & Replacement Guide',
    description:
      'A creaking BB often isn\'t the BB. Diagnose the 5 most common creak sources, check bearing wear, and know when your 3,000–10,000-mile bottom bracket is due.',
    category: 'maintenance',
    tags: ['bottom bracket', 'bottom bracket creaking', 'bike maintenance', 'press-fit', 'drivetrain'],
    datePublished: '2026-06-21',
    dateModified: '2026-06-21',
    heroImage: '/images/articles/bottom-bracket-creaking.webp',
    heroImageAlt:
      'Bike mechanic working on a bicycle drivetrain in a clean professional workshop with tools organized on the wall',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['bike-maintenance-schedule', 'when-to-replace-cassette'],
  },
  {
    slug: 'dropper-post-maintenance',
    title: 'Dropper Post Maintenance: Service Intervals & Care',
    description:
      'Service your dropper post every 100–200 ride hours. Learn the sag and slow-return warning signs, daily care tips, and when a shop visit saves the post.',
    category: 'maintenance',
    tags: ['dropper post', 'dropper post maintenance', 'mountain bike', 'MTB', 'bike maintenance'],
    datePublished: '2026-06-20',
    dateModified: '2026-06-20',
    heroImage: '/images/articles/dropper-post-maintenance.webp',
    heroImageAlt:
      'Mountain biker descending a technical trail with dropper post visible, natural outdoor lighting, action shot',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['bike-maintenance-schedule', 'suspension-service-intervals'],
  },
  {
    slug: 'suspension-service-intervals',
    title: 'Fork & Shock Service Intervals: The Hour-Based Guide',
    description:
      'Service your MTB fork every 50 hours, full damper rebuild at 100–200 hours. Learn the symptoms, Fox vs. RockShox intervals, and why delay costs more.',
    category: 'maintenance',
    tags: ['MTB suspension', 'fork service', 'shock service', 'suspension maintenance', 'mountain bike'],
    datePublished: '2026-06-19',
    dateModified: '2026-06-19',
    heroImage: '/images/articles/suspension-service-intervals.webp',
    heroImageAlt:
      'Mountain bike fork suspension detail close-up on a trail, natural outdoor lighting, ultra-realistic 16:9',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 8,
    related: ['bike-maintenance-schedule', 'dropper-post-maintenance'],
  },
  {
    slug: 'tubeless-sealant-how-often',
    title: 'How Often to Add Tubeless Sealant (Hours & Months)',
    description:
      'Refresh tubeless sealant every 2–6 months or 40–60 ride hours. Learn the dipstick check, when to top up vs. fully refresh, and signs sealant has dried out.',
    category: 'maintenance',
    tags: ['tubeless sealant', 'tubeless tires', 'maintenance', 'MTB', 'tire maintenance'],
    datePublished: '2026-06-18',
    dateModified: '2026-06-18',
    heroImage: '/images/articles/tubeless-sealant-how-often.webp',
    heroImageAlt:
      'Mountain bike tire on rocky trail showing knobby tread close-up, outdoor natural lighting',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['bike-maintenance-schedule', 'when-to-replace-bike-tires'],
  },
  {
    slug: 'when-to-replace-bike-tires',
    title: 'When to Replace Bike Tires: Mileage & 6 Wear Signs',
    description:
      'Bike tires last 1,000–3,000 miles on the road, less for MTB. Six wear signs — squared tread, casing threads, sidewall cracks — tell you when to replace.',
    category: 'maintenance',
    tags: ['bike tires', 'tire wear', 'maintenance', 'MTB', 'road bike'],
    datePublished: '2026-06-17',
    dateModified: '2026-06-17',
    heroImage: '/images/articles/when-to-replace-bike-tires.webp',
    heroImageAlt:
      'Mountain bike tire on rocky trail showing knobby tread close-up, outdoor natural lighting, ultra-realistic 16:9',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 8,
    related: ['bike-maintenance-schedule', 'tubeless-sealant-how-often', 'pre-ride-bike-check'],
  },
  {
    slug: 'how-often-bleed-disc-brakes',
    title: 'How Often to Bleed Disc Brakes (MTB & Road)',
    description:
      'Bleed disc brakes every 6–12 months or when the lever feels spongy. Learn mineral oil vs. DOT fluid intervals, warning signs, and when to visit a shop.',
    category: 'maintenance',
    tags: ['disc brakes', 'brake bleed', 'brake maintenance', 'mineral oil', 'DOT fluid'],
    datePublished: '2026-06-16',
    dateModified: '2026-06-16',
    heroImage: '/images/articles/how-often-bleed-disc-brakes.webp',
    heroImageAlt: 'Mountain bike hydraulic disc brake caliper and rotor detail close-up on a dusty trail, natural light',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['bike-maintenance-schedule', 'when-to-replace-brake-pads', 'when-to-replace-brake-rotors'],
  },
  {
    slug: 'when-to-replace-brake-rotors',
    title: 'When to Replace Bike Brake Rotors (Thickness Guide)',
    description:
      'Bike rotors need replacement at 1.5 mm thickness. Learn to measure with calipers, spot warping vs. contamination, and use the 2–4 pad-set lifespan rule.',
    category: 'maintenance',
    tags: ['brake rotors', 'disc brakes', 'brakes', 'maintenance', 'rotor wear'],
    datePublished: '2026-06-13',
    dateModified: '2026-06-13',
    heroImage: '/images/articles/when-to-replace-brake-rotors.webp',
    heroImageAlt: 'Mountain bike disc brake rotor and hydraulic caliper close-up with trail background, natural light',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['bike-maintenance-schedule', 'when-to-replace-brake-pads', 'how-often-bleed-disc-brakes'],
  },
  {
    slug: 'when-to-replace-brake-pads',
    title: 'When to Replace Bike Brake Pads: Wear Signs & Intervals',
    description:
      'Resin pads last 500–1,000 miles; metallic up to 1,500. Learn the 1.5 mm minimum, how to spot worn pads by sound and feel, and how to bed in replacements.',
    category: 'maintenance',
    tags: ['brake pads', 'disc brakes', 'brakes', 'maintenance', 'brake wear'],
    datePublished: '2026-06-12',
    dateModified: '2026-06-12',
    heroImage: '/images/articles/when-to-replace-brake-pads.webp',
    heroImageAlt: 'Mountain bike disc brake rotor and caliper close-up detail on a trail, shallow depth of field',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['bike-maintenance-schedule', 'when-to-replace-brake-rotors', 'how-often-bleed-disc-brakes'],
  },
  {
    slug: 'when-to-replace-cassette',
    title: 'When to Replace Your Cassette (and Chainrings)',
    description:
      'Replace your cassette every 2–3 chains to avoid skipping and expensive repairs. Learn the wear signs, shark-tooth test, and chainring replacement timing.',
    category: 'maintenance',
    tags: ['cassette', 'chainring', 'drivetrain', 'maintenance', 'cassette wear'],
    datePublished: '2026-06-11',
    dateModified: '2026-06-11',
    heroImage: '/images/articles/when-to-replace-cassette.webp',
    heroImageAlt: 'Bicycle cassette showing worn teeth and drivetrain close-up on a mountain bike',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['bike-maintenance-schedule', 'when-to-replace-bike-chain', 'how-to-measure-chain-wear'],
  },
  {
    slug: 'how-to-measure-chain-wear',
    title: 'How to Measure Chain Wear: Checker Tool & Ruler Methods',
    description:
      'Step-by-step guide to measuring bike chain wear with a chain checker or 12-inch ruler. Know the 0.5% threshold and when to replace before cassette damage occurs.',
    category: 'maintenance',
    tags: ['chain wear', 'chain checker', 'drivetrain', 'maintenance', 'chain measurement'],
    datePublished: '2026-06-11',
    dateModified: '2026-06-11',
    heroImage: '/images/articles/how-to-measure-chain-wear.webp',
    heroImageAlt:
      'Red Park Tool chain wear indicator gauge inserted into bicycle chain links, macro close-up',
    author: 'KOR Cycling Team',
    schemaType: 'HowTo',
    readingTime: 6,
    related: ['bike-maintenance-schedule', 'when-to-replace-bike-chain', 'when-to-replace-cassette'],
  },
  {
    slug: 'when-to-replace-bike-chain',
    title: 'When to Replace Your Bike Chain (Mileage + Wear Signs)',
    description:
      'Know exactly when to replace your bike chain: the 0.5% wear rule, mileage ranges by speed, and the cost of waiting too long. Drivetrain lifespan explained.',
    category: 'maintenance',
    tags: ['chain', 'drivetrain', 'maintenance', 'chain wear', 'chain replacement'],
    datePublished: '2026-06-11',
    dateModified: '2026-06-11',
    heroImage: '/images/articles/when-to-replace-bike-chain.webp',
    heroImageAlt: 'Close-up of a bicycle chain and cassette showing drivetrain wear on a mountain bike',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 7,
    related: ['bike-maintenance-schedule', 'how-to-measure-chain-wear', 'when-to-replace-cassette'],
  },
  {
    slug: 'bike-maintenance-schedule',
    title: 'Bike Maintenance Schedule: What to Service and When',
    description:
      'Complete bike maintenance schedule: chain, cassette, brakes, tires, suspension & more — with mileage intervals, checklists, and a master component table.',
    category: 'maintenance',
    tags: ['maintenance', 'bike care', 'chain', 'brakes', 'tires', 'suspension'],
    datePublished: '2026-06-11',
    dateModified: '2026-06-11',
    heroImage: '/images/articles/bike-maintenance-schedule.webp',
    heroImageAlt: 'Cyclist performing maintenance on a clean mountain bike outdoors in natural light',
    author: 'KOR Cycling Team',
    schemaType: 'Article',
    readingTime: 12,
    related: ['when-to-replace-bike-chain', 'how-to-measure-chain-wear', 'when-to-replace-cassette'],
  },
];
